# Generated by Django 3.0.8 on 2020-07-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.CharField(default=True, max_length=25),
            preserve_default=False,
        ),
    ]
